# Generated by Django 5.1.7 on 2025-03-15 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AREA', models.CharField(blank=True, max_length=255, null=True)),
                ('DIRECCION_HECHO', models.CharField(blank=True, max_length=255, null=True)),
                ('BARRIO_HECHO', models.CharField(blank=True, max_length=255, null=True)),
                ('Cordenada_Geografica', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AÑO', models.IntegerField()),
                ('FECHA', models.DateField()),
                ('DIA', models.CharField(max_length=20)),
                ('HORA', models.TimeField()),
                ('CONTROLES_DE_TRANSITO', models.CharField(blank=True, max_length=255, null=True)),
                ('CLASE_DE_ACCIDENTE', models.CharField(max_length=100)),
                ('CLASE_DE_SERVICIO', models.CharField(max_length=100)),
                ('GRAVEDAD_DEL_ACCIDENTE', models.CharField(max_length=100)),
                ('CLASE_DE_VEHICULO', models.CharField(max_length=100)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidente.ubicacion')),
            ],
        ),
    ]
