# Generated by Django 5.1.7 on 2025-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidente',
            name='HORA',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
