# Generated by Django 5.1.7 on 2025-03-28 20:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidente', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroide', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('total_accidentes', models.PositiveIntegerField()),
                ('area_cluster', models.FloatField(help_text='Área aproximada del cluster en metros cuadrados')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
