# Generated by Django 5.1.7 on 2025-03-30 03:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidente', '0003_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroide', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accident_count', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
